(()=>{
 const form=document.querySelector('.form-card form');if(!form)return;
 const $=(s,p=document)=>p.querySelector(s),$$=(s,p=document)=>[...p.querySelectorAll(s)];
 const base=()=>[...form.querySelectorAll(':scope > fieldset:not(.review-step)')].filter(x=>!x.hidden);
 const review=document.createElement('fieldset');review.className='review-step wizard-review';review.innerHTML='<legend><span>✓</span> Revisar y confirmar</legend><div class="review-grid" id="reviewGrid"></div>';form.insertBefore(review,form.querySelector('footer'));
 let step=0,user=null;
 const primary=$('.primary',form),prev=$('.wizard-prev',form),draft=$('.wizard-draft',form),bar=$('#wizardBar'),stepText=$('#wizardStep'),percent=$('#wizardPercent'),label=$('#wizardLabel');
 const labels=['Datos personales','Ubicación','Seguro solicitado','Datos específicos','Revisión final'];
 function steps(){return [...base(),review]}
 function clearErrors(scope=form){$$('.field-message',scope).forEach(x=>x.remove());$$('.input.error',scope).forEach(x=>x.classList.remove('error'))}
 function message(el,text){const box=el.closest('.input')||el.closest('label')||el;box.classList.add('error');const m=document.createElement('small');m.className='field-message';m.textContent=text;(el.closest('label')||box).append(m)}
 function validCurrent(){const current=steps()[step];clearErrors(current);if(current===review)return true;let ok=true;const controls=$$('input,select,textarea',current).filter(x=>x.type!=='radio'&&!x.closest('[hidden]')&&!x.disabled);for(const el of controls){let required=true;if(el.id==='lifeAddress')required=false;if(el.type==='file'){if(!el.files?.length){message(el,'Adjuntá la foto o PDF de la tarjeta.');ok=false}continue}if(el.type==='checkbox'){if(!el.checked){message(el,'Tenés que aceptar la declaración.');ok=false}continue}if(required&&!String(el.value||'').trim()){message(el,'Este campo es obligatorio.');ok=false}}
  const dni=$('#commonDni');if(current.contains(dni)&&!/^[0-9]{7,9}$/.test(dni.value.replace(/\D/g,''))){message(dni,'Ingresá un DNI de 7 a 9 números.');ok=false}
  const mail=$('#commonEmail');if(current.contains(mail)&&mail.value&&!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(mail.value)){message(mail,'Ingresá un correo válido.');ok=false}
  if(!ok)current.querySelector('.error input,.error select,.error textarea')?.focus();return ok
 }
 function reviewData(){const type=$('#insuranceType').value,data=[['Cliente',$('#commonName').value],['DNI',$('#commonDni').value],['Nacimiento',$('#commonBirth').value],['Teléfono',$('#commonPhone').value],['Correo',$('#commonEmail').value],['Domicilio',$('#commonAddress').value],['Ubicación',`${$('#commonLocality').value}, ${$('#commonProvince').value}`],['Seguro',type],['Monto',`$ ${$('#commonAmount').value}`]];if(['Seguro de vehículo','Moto'].includes(type)){data.push(['Año',$('#vehicleYear').value],['Código postal',$('#vehiclePostal').value],['Tarjeta',$('#vehicleCard').files?.[0]?.name||'Sin archivo']);if(type==='Seguro de vehículo')data.push(['Uso',$('#vehicleUse').value],['GNC',$('#vehicleGnc').value==='true'?'Sí':'No'])}if(['Vida','Vida ART 90 y Sepelio'].includes(type))data.push(['Suma asegurada',`$ ${$('#lifeCoverage').value}`],['Cuota',`$ ${$('#lifePremium').value}`],['Beneficiarios',$('#lifeBeneficiary').value]);$('#reviewGrid').innerHTML=data.map(([k,v])=>`<div><small>${escapeHtml(k)}</small><b>${escapeHtml(v||'Sin dato')}</b></div>`).join('')}
 function render(){const all=steps();if(step>=all.length)step=all.length-1;all.forEach((x,i)=>x.classList.toggle('wizard-hidden',i!==step));const pct=Math.round((step+1)/all.length*100);bar.style.width=`${pct}%`;stepText.textContent=`Paso ${step+1} de ${all.length}`;percent.textContent=`${pct}%`;label.textContent=labels[step===all.length-1?4:Math.min(step,3)];prev.hidden=step===0;primary.textContent=step===all.length-1?'Enviar solicitud ✓':'Continuar →';if(step===all.length-1)reviewData();window.scrollTo({top:Math.max(0,form.getBoundingClientRect().top+scrollY-100),behavior:'smooth'})}
 function escapeHtml(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function collect(){const ids=['commonName','commonDni','commonBirth','commonPhone','commonEmail','commonAddress','commonProvince','commonLocality','insuranceType','commonAmount','vehicleYear','vehiclePostal','vehicleUse','vehicleGnc','lifeCoverage','lifePremium','lifeFuneral','lifePayment','lifeReference','lifeConditions','lifeBeneficiary'];const data={};ids.forEach(id=>{const el=$(`#${id}`);if(el)data[id]=el.value});data.lifeAccepted=$('#lifeAccepted')?.checked||false;return data}
 function restore(data={}){Object.entries(data).forEach(([id,value])=>{const el=$(`#${id}`);if(el){if(el.type==='checkbox')el.checked=!!value;else el.value=value}});const type=data.insuranceType;if(type){const radio=$(`input[name="seller_insurance_choice"][value="${CSS.escape(type)}"]`);if(radio)radio.checked=true;$('#insuranceType').dispatchEvent(new Event('change'))}}
 async function saveDraft(){if(!user)return toast('Esperá un momento','Todavía estamos conectando tu cuenta.','error');const {error}=await window.PSPAuth.client.from('request_drafts').upsert({seller_id:user.user.id,form_data:collect(),current_step:step});if(error)return fail(error);toast('Borrador guardado','Podés cerrar la página y continuar más tarde.')}
 async function loadDraft(){const {data,error}=await window.PSPAuth.client.from('request_drafts').select('form_data,current_step').eq('seller_id',user.user.id).maybeSingle();if(error)return fail(error);if(data){restore(data.form_data);step=Math.min(data.current_step,steps().length-1);render();toast('Borrador recuperado','Continuá desde donde lo dejaste.')}}
 primary.addEventListener('click',async()=>{if(!validCurrent())return;if(step<steps().length-1){step++;render();return}primary.disabled=true;primary.textContent='Enviando...';const ok=await window.submit();primary.disabled=false;if(ok){await window.PSPAuth.client.from('request_drafts').delete().eq('seller_id',user.user.id);step=0;render()}else primary.textContent='Enviar solicitud ✓'});
 prev.addEventListener('click',()=>{if(step>0){step--;render()}});draft.addEventListener('click',saveDraft);
 $$('input[name="seller_insurance_choice"]').forEach(x=>x.addEventListener('change',()=>{if(step>=steps().length)step=steps().length-1;render()}));
 $$('[data-plan-type]').forEach(btn=>btn.addEventListener('click',()=>{const type=btn.dataset.planType,radio=$(`input[name="seller_insurance_choice"][value="${CSS.escape(type)}"]`);radio.checked=true;radio.dispatchEvent(new Event('change',{bubbles:true}));$('#lifeCoverage').value=btn.dataset.coverage;$('#lifePremium').value=btn.dataset.premium;document.querySelector('#solicitud').scrollIntoView({behavior:'smooth',block:'start'});toast('Plan seleccionado',`${type}: $${Number(btn.dataset.coverage).toLocaleString('es-AR')}`)}));
 const card=$('#vehicleCard');card?.addEventListener('change',()=>{document.querySelector('.file-preview')?.remove();const file=card.files?.[0];if(!file)return;const box=document.createElement('div');box.className='file-preview';box.innerHTML=`<span>${file.type.startsWith('image/')?'Vista previa':'Documento PDF'}</span><b>${escapeHtml(file.name)}</b><button type="button">Quitar</button>`;if(file.type.startsWith('image/')){const img=document.createElement('img');img.src=URL.createObjectURL(file);box.prepend(img)}box.querySelector('button').onclick=()=>{card.value='';box.remove();$('#vehicleCardName').textContent='Ningún archivo seleccionado'};card.closest('label').append(box)});
 function start(e){user=e.detail;loadDraft();render()}window.addEventListener('psp:authenticated',start,{once:true});if(document.body.classList.contains('auth-authorized'))window.PSPAuth.currentUser().then(x=>{if(x)start({detail:x})});render();
})();