-- PSP Seguros: esquema inicial para Supabase/Postgres
-- Ejecutar mediante Supabase CLI o desde el SQL Editor del proyecto.

create extension if not exists pgcrypto;

do $$ begin
  create type public.user_role as enum ('admin', 'seller');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.request_status as enum ('pending', 'in_review', 'issued', 'rejected');
exception when duplicate_object then null;
end $$;

do $$ begin
  create type public.help_status as enum ('new', 'in_progress', 'resolved');
exception when duplicate_object then null;
end $$;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text not null check (char_length(trim(full_name)) between 2 and 120),
  role public.user_role not null default 'seller',
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.insurance_requests (
  id uuid primary key default gen_random_uuid(),
  request_number bigint generated by default as identity unique,
  seller_id uuid not null references public.profiles(id) on delete restrict,
  client_dni varchar(9) not null check (client_dni ~ '^[0-9]{7,9}$'),
  province text not null check (char_length(trim(province)) between 2 and 80),
  locality text not null check (char_length(trim(locality)) between 2 and 100),
  insurance_type text not null check (
    insurance_type in (
      'Automotor',
      'Hogar',
      'Vida',
      'Comercio',
      'Accidentes personales',
      'Responsabilidad civil',
      'Otro'
    )
  ),
  amount numeric(14,2) not null check (amount > 0),
  status public.request_status not null default 'pending',
  admin_notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.help_requests (
  id uuid primary key default gen_random_uuid(),
  seller_id uuid not null references public.profiles(id) on delete cascade,
  insurance_request_id uuid references public.insurance_requests(id) on delete set null,
  message text not null check (char_length(trim(message)) between 3 and 2000),
  status public.help_status not null default 'new',
  admin_response text,
  responded_by uuid references public.profiles(id) on delete set null,
  responded_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint response_requires_admin check (
    (admin_response is null and responded_by is null and responded_at is null)
    or
    (admin_response is not null and responded_by is not null and responded_at is not null)
  )
);

create index if not exists insurance_requests_seller_idx
  on public.insurance_requests (seller_id, created_at desc);
create index if not exists insurance_requests_status_idx
  on public.insurance_requests (status, created_at desc);
create index if not exists help_requests_seller_idx
  on public.help_requests (seller_id, created_at desc);
create index if not exists help_requests_status_idx
  on public.help_requests (status, created_at desc);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
set search_path = ''
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_set_updated_at on public.profiles;
create trigger profiles_set_updated_at
before update on public.profiles
for each row execute function public.set_updated_at();

drop trigger if exists insurance_requests_set_updated_at on public.insurance_requests;
create trigger insurance_requests_set_updated_at
before update on public.insurance_requests
for each row execute function public.set_updated_at();

drop trigger if exists help_requests_set_updated_at on public.help_requests;
create trigger help_requests_set_updated_at
before update on public.help_requests
for each row execute function public.set_updated_at();

-- Los usuarios nuevos siempre nacen como vendedores. El rol administrador
-- se asigna manualmente desde SQL para impedir que un usuario se autoproclame admin.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  insert into public.profiles (id, full_name, role)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'full_name'), ''), split_part(new.email, '@', 1)),
    'seller'
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute function public.handle_new_user();

create schema if not exists private;
revoke all on schema private from public, anon;
grant usage on schema private to authenticated;

create or replace function private.is_admin()
returns boolean
language sql
stable
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.profiles
    where id = (select auth.uid())
      and role = 'admin'
      and active = true
  );
$$;

revoke all on function private.is_admin() from public, anon;
grant execute on function private.is_admin() to authenticated;

alter table public.profiles enable row level security;
alter table public.insurance_requests enable row level security;
alter table public.help_requests enable row level security;

drop policy if exists "profiles_select_own_or_admin" on public.profiles;
create policy "profiles_select_own_or_admin"
on public.profiles for select
to authenticated
using (id = (select auth.uid()) or (select private.is_admin()));

drop policy if exists "profiles_admin_update" on public.profiles;
create policy "profiles_admin_update"
on public.profiles for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

drop policy if exists "requests_select_own_or_admin" on public.insurance_requests;
create policy "requests_select_own_or_admin"
on public.insurance_requests for select
to authenticated
using (seller_id = (select auth.uid()) or (select private.is_admin()));

drop policy if exists "requests_seller_insert_own" on public.insurance_requests;
create policy "requests_seller_insert_own"
on public.insurance_requests for insert
to authenticated
with check (
  seller_id = (select auth.uid())
  and exists (
    select 1 from public.profiles
    where id = (select auth.uid()) and active = true
  )
);

drop policy if exists "requests_admin_update" on public.insurance_requests;
create policy "requests_admin_update"
on public.insurance_requests for update
to authenticated
using ((select private.is_admin()))
with check ((select private.is_admin()));

drop policy if exists "requests_admin_delete" on public.insurance_requests;
create policy "requests_admin_delete"
on public.insurance_requests for delete
to authenticated
using ((select private.is_admin()));

drop policy if exists "help_select_own_or_admin" on public.help_requests;
create policy "help_select_own_or_admin"
on public.help_requests for select
to authenticated
using (seller_id = (select auth.uid()) or (select private.is_admin()));

drop policy if exists "help_seller_insert_own" on public.help_requests;
create policy "help_seller_insert_own"
on public.help_requests for insert
to authenticated
with check (seller_id = (select auth.uid()) and status = 'new');

drop policy if exists "help_admin_update" on public.help_requests;
create policy "help_admin_update"
on public.help_requests for update
to authenticated
using ((select private.is_admin()))
with check (
  (select private.is_admin())
  and (responded_by is null or responded_by = (select auth.uid()))
);

grant usage on schema public to authenticated;
grant select, update on public.profiles to authenticated;
grant select, insert on public.insurance_requests to authenticated;
grant select, insert on public.help_requests to authenticated;
grant update, delete on public.insurance_requests to authenticated;
grant update on public.help_requests to authenticated;
grant usage, select on sequence public.insurance_requests_request_number_seq to authenticated;

comment on table public.profiles is 'Perfiles y roles de usuarios autenticados de PSP.';
comment on table public.insurance_requests is 'Solicitudes de seguros ingresadas por vendedores.';
comment on table public.help_requests is 'Consultas de vendedores dirigidas a administración.';

