"use client";
import { FormEvent, useMemo, useState } from "react";

type Sale={id:string;client:string;type:string;seller:string;date:string;amount:number;status:string};
const seed:Sale[]=[
{id:"PSP-1048",client:"María González",type:"Automotor",seller:"Lucía Fernández",date:"Hoy, 10:32",amount:48500,status:"Pendiente"},
{id:"PSP-1047",client:"Carlos Ramírez",type:"Hogar",seller:"Nicolás Suárez",date:"Hoy, 09:18",amount:27200,status:"En proceso"},
{id:"PSP-1046",client:"Ana Martínez",type:"Vida",seller:"Sofía López",date:"Ayer, 17:46",amount:36400,status:"Emitida"},
{id:"PSP-1045",client:"Diego Benítez",type:"Automotor",seller:"Lucía Fernández",date:"Ayer, 15:21",amount:52100,status:"Emitida"},
{id:"PSP-1044",client:"Valentina Rossi",type:"Comercio",seller:"Martín Acosta",date:"14 Jul, 12:05",amount:61800,status:"Pendiente"}];
const team=[{n:"Lucía Fernández",i:"LF",v:18,a:"$ 864.200",p:92},{n:"Nicolás Suárez",i:"NS",v:14,a:"$ 672.500",p:74},{n:"Sofía López",i:"SL",v:11,a:"$ 528.900",p:58},{n:"Martín Acosta",i:"MA",v:8,a:"$ 384.600",p:42}];
const money=new Intl.NumberFormat("es-AR",{style:"currency",currency:"ARS",maximumFractionDigits:0});
export default function Home(){
 const [sales,setSales]=useState(seed),[modal,setModal]=useState(false),[query,setQuery]=useState(""),[filter,setFilter]=useState("Todos"),[toast,setToast]=useState(false);
 const visible=useMemo(()=>sales.filter(s=>(filter==="Todos"||s.status===filter)&&`${s.client} ${s.id} ${s.seller}`.toLowerCase().includes(query.toLowerCase())),[sales,filter,query]);
 function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setSales(x=>[{id:`PSP-${1044+x.length+1}`,client:String(f.get("client")),type:String(f.get("type")),seller:String(f.get("seller")),date:"Ahora",amount:Number(f.get("amount")),status:"Pendiente"},...x]);setModal(false);setToast(true);setTimeout(()=>setToast(false),3000)}
 return <main className="shell">
  <aside><div className="logo"><b>P</b><span><strong>PSP</strong><small>SEGUROS</small></span></div><p>GESTIÓN</p>{[["▦","Resumen"],["↗","Ventas"],["＋","Nueva solicitud"],["♙","Clientes"]].map(([i,n])=><button className={n==="Resumen"?"on":""} key={n} onClick={()=>n==="Nueva solicitud"&&setModal(true)}><i>{i}</i>{n}{n==="Nueva solicitud"&&<em>Nuevo</em>}</button>)}<p>EQUIPO</p>{[["♧","Vendedores"],["⌁","Rendimiento"],["▥","Reportes"]].map(([i,n])=><button key={n}><i>{i}</i>{n}</button>)}<div className="help"><b>?</b><strong>¿Necesitás ayuda?</strong><small>Consultá nuestra guía rápida</small><a>Ver guía</a></div><div className="user"><span>DMP</span><div><b>Diego Martin Poccioni</b><small>Administrador</small></div>⋮</div></aside>
  <section className="content"><header><label>⌕ <input placeholder="Buscar clientes, pólizas..." value={query} onChange={e=>setQuery(e.target.value)}/><kbd>⌘ K</kbd></label><div>♢ <span>DMP</span></div></header><div className="body">
   <div className="welcome"><div><p>JUEVES, 16 DE JULIO</p><h1>Buenos días, Diego 👋</h1><small>Este es el resumen de la actividad de tu equipo.</small></div><button className="primary" onClick={()=>setModal(true)}>＋ Nueva solicitud</button></div>
   <section className="metrics">{[["↗","Ventas este mes","51","vs. 45 el mes pasado","↗ 12,5%","blue"],["$","Prima total","$ 2.450.200","vs. $ 2.264.500 anterior","↗ 8,2%","green"],["◷","Solicitudes pendientes","12","Requieren tu atención","6 nuevas","orange"],["♧","Vendedores activos","8","de 10 vendedores totales","↗ 2","purple"]].map(x=><article key={x[1]}><i className={x[5]}>{x[0]}</i><em>{x[4]}</em><p>{x[1]}</p><h2>{x[2]}</h2><small>{x[3]}</small></article>)}</section>
   <section className="main-grid"><article className="panel"><div className="head"><div><h3>Rendimiento de ventas</h3><p>Ventas generadas en los últimos 6 meses</p></div><select><option>Últimos 6 meses</option></select></div><div className="chart">{[["Feb",32],["Mar",45],["Abr",38],["May",50],["Jun",42],["Jul",57]].map(x=><div key={x[0]}><span>{x[1]}</span><i style={{height:`${Number(x[1])*2.45}px`}}/><small>{x[0]}</small></div>)}</div><div className="foot">■ Ventas realizadas <b>Promedio mensual: <strong>44 ventas</strong></b></div></article>
   <article className="panel rank"><div className="head"><div><h3>Top vendedores</h3><p>Rendimiento del mes actual</p></div><a>Ver todos →</a></div>{team.map((t,i)=><div className="seller" key={t.n}><b>{i+1}</b><span>{t.i}</span><div><strong>{t.n}<em>{t.a}</em></strong><i><u style={{width:`${t.p}%`}}/></i><small>{t.v} ventas</small></div></div>)}</article></section>
   <section className="panel recent"><div className="head"><div><h3>Solicitudes recientes</h3><p>Últimas solicitudes ingresadas por el equipo</p></div><div className="filters"><label>⌕ <input placeholder="Buscar..." value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={filter} onChange={e=>setFilter(e.target.value)}><option>Todos</option><option>Pendiente</option><option>En proceso</option><option>Emitida</option></select><a>Ver todas →</a></div></div><div className="table"><table><thead><tr><th>CLIENTE</th><th>TIPO DE SEGURO</th><th>VENDEDOR</th><th>FECHA</th><th>PRIMA</th><th>ESTADO</th><th/></tr></thead><tbody>{visible.map(s=><tr key={s.id}><td><div className="client"><span>{s.client.split(" ").map(x=>x[0]).slice(0,2)}</span><div><b>{s.client}</b><small>{s.id}</small></div></div></td><td>{s.type}</td><td>{s.seller}</td><td>{s.date}</td><td><b>{money.format(s.amount)}</b></td><td><em className={s.status.replace(" ","").toLowerCase()}>{s.status}</em></td><td>•••</td></tr>)}</tbody></table>{!visible.length&&<p className="empty">No encontramos solicitudes.</p>}</div></section>
  </div></section>
  {modal&&<div className="backdrop" onMouseDown={e=>e.currentTarget===e.target&&setModal(false)}><section className="modal"><div className="modal-head"><div><small>NUEVA SOLICITUD</small><h2>Datos del asegurado</h2><p>Completá la información para que administración emita la póliza.</p></div><button onClick={()=>setModal(false)}>×</button></div><form onSubmit={submit}><div className="form"><label className="wide">Nombre completo<input name="client" required placeholder="Ej. Juan Pérez"/></label><label>DNI / CUIT<input required placeholder="00.000.000"/></label><label>Teléfono<input required placeholder="+54 9 11..."/></label><label>Email<input type="email" placeholder="cliente@email.com"/></label><label>Tipo de seguro<select name="type" required defaultValue=""><option value="" disabled>Seleccionar</option><option>Automotor</option><option>Hogar</option><option>Vida</option><option>Comercio</option></select></label><label>Vendedor<select name="seller"><option>Lucía Fernández</option><option>Nicolás Suárez</option><option>Sofía López</option><option>Martín Acosta</option></select></label><label>Prima estimada<input name="amount" type="number" min="1" required placeholder="$ 0"/></label><label className="wide">Observaciones<textarea placeholder="Cobertura solicitada, datos del vehículo, aclaraciones..."/></label></div><footer><button type="button" onClick={()=>setModal(false)}>Cancelar</button><button className="primary">Enviar solicitud →</button></footer></form></section></div>}
  {toast&&<div className="toast"><b>✓</b><span><strong>Solicitud enviada</strong><small>Ya está disponible para administración.</small></span></div>}
 </main>
}
